import os
import psycopg2
from datetime import date

# Load connection parameters from environment (same as other scripts)
HOST = os.getenv('POSTGRES_HOST', 'localhost')
DB   = os.getenv('POSTGRES_DB', 'ksp_intelligence')
USER = os.getenv('POSTGRES_USER', 'ksp_app')
PASS = os.getenv('POSTGRES_PASSWORD', 'changeme')

def main():
    conn = psycopg2.connect(host=HOST, dbname=DB, user=USER, password=PASS)
    cur = conn.cursor()
    # Insert a simple CaseMaster row using the serial generator function
    # Using dummy IDs for foreign‑key columns that are not present in this minimal schema
    cur.execute(
        """
        INSERT INTO casemaster (
            CrimeNo,
            CrimeRegisteredDate,
            latitude,
            longitude,
            BriefFacts
        ) VALUES (
            get_next_crime_no(1::INT, 1::INT, 1::INT, %s),
            %s,
            12.9716,
            77.5946,
            'Demo case generated by generate_full.py'
        ) RETURNING CaseMasterID;
        """,
        (date.today().year, date.today())
    )
    cm_id = cur.fetchone()[0]
    conn.commit()
    print(f"Inserted CaseMaster ID {cm_id} with CrimeNo generated via get_next_crime_no")
    cur.close()
    conn.close()

if __name__ == "__main__":
    main()
